coffeedapp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

# urlpatterns = [
#     url(r'^admin/', include(admin.site.urls)),
# ]


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
	(r'', include('core.urls')),
)

core/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required, permission_required # to block users who are not logged is so that cannot create
# all url that we want to protect we add login_required()

# from django.contrib import admin
import core.views as coreviews

urlpatterns = patterns('',

	url(r'^$', coreviews.LandingView.as_view()),
	url(r'location/$', coreviews.LocationListView.as_view()),

	# Registering the url for search
	url(r'search/$', coreviews.SearchListView.as_view()),


	# for url location/1/detail
	# pk stands for Primary Key
	# $ to capture any wording after the url
	url(r'location/(?P<pk>\d+)/detail/$', coreviews.LocationDetailView.as_view(), name = 'location_list'),
	# name = 'location_list' has been added so we can use it into our Model and changing the label of details
	# has no longer impact on our other codes. Using it thru reverse function

	url(r'location/create/$', login_required(coreviews.LocationCreateView.as_view())),
	# LocationCreateView isa name we defined in views.py in the Core folder


	url(r'location/(?P<pk>\d+)/update/$', permission_required('is_staff')(coreviews.LocationUpdateView.as_view()), name = 'location_update'),


	#now the url to create and update a review
	url(r'location/(?P<pk>\d+)/review/create/$', login_required(coreviews.ReviewCreateView.as_view()), name = 'review_create'),
	url(r'location/(?P<pk>\d+)/review/update/$', login_required(coreviews.ReviewUpdateView.as_view()), name = 'review_update'),


	# Registering the entrance login page
	url(r'entrance/$', coreviews.entrance),

	# easy url to logout
	url(r'^logout/$', 'django.contrib.auth.views.logout',{'next_page': '/entrance'})
		# next page coulb be our /entrance
)

core/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db.models import Avg
from geoposition.fields import GeopositionField # adding maps to backends


import os
import uuid

# In models.py you can write:
# from FTPStorage import FTPStorage
# fs = FTPStorage()
# class FTPTest(models.Model):
# 	file = models.FileField(upload_to='a/b/c/', storage=fs)


# we create a cateogry
RATING_CHOICES = (
	(0, 'None'),
	(1, '*'),
	(2, '**'),
	(3, '***'),
	(4, '****'),
	(5, '*****'),
	)

YESNO_CHOICES = (
	(0, 'No'),
	(1, 'Yes')
	)

PLURAL_CHOICES = (
	(0, 'None'),
	(1, 'Minimal'),
	(2, 'Some'),
	(3, 'Ample')
	)

WIFI_CHOICES = (
	(0, 'None'),
	(1, 'Spotty'),
	(2, 'Strong')
	)

COFFEE_CHOICES = (
	(0, 'None'),
	(1, 'Truck Stop'),
	(2, 'Good'),
	(3, 'Really Good'),
	(4, 'Great'),
	)

def upload_to_location(instance, filename):
    blocks = filename.split('.')
    ext = blocks[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    instance.title = blocks[0]
    return os.path.join('uploads/', filename)

# Create your models here.
# be careful, not doing copy/paste, use Tab
# this will show that we are in the same object
# avoid any spaces

class Location(models.Model):
	title = models.CharField(max_length=300)
 	description = models.TextField(null=True, blank=True) 
 	address = models.TextField(null=True, blank=True) 

	position = GeopositionField(null=True, blank=True)

 	hours = models.TextField(null=True, blank=True) 
 	image_file = models.ImageField(upload_to=upload_to_location, null=True, blank=True)

	wifi = models.IntegerField(choices=WIFI_CHOICES, null=True, blank=True)
	seating = models.IntegerField(choices=PLURAL_CHOICES, null=True, blank=True)
	outlets = models.IntegerField(choices=PLURAL_CHOICES, null=True, blank=True)
	bathrooms = models.IntegerField(choices=YESNO_CHOICES, null=True, blank=True)
	coffee = models.IntegerField(choices=COFFEE_CHOICES, null=True, blank=True)
	alcohol = models.IntegerField(choices=YESNO_CHOICES, null=True, blank=True)
	outdoor = models.IntegerField(choices=YESNO_CHOICES, null=True, blank=True)
	food = models.IntegerField(choices=YESNO_CHOICES, null=True, blank=True)

 	created_at = models.DateTimeField(auto_now_add=True)

 	# Code below allow us to define the title of the object in the Admin section
 	def __unicode__(self):
 		return self.title
 		
 	def get_absolute_url(self):
 		# return "location/"+str(self.id)+"/detail" # not the best way to do it
 		# instead use the core.urlresolvers
 		return reverse (viewname="location_list", args=[self.id])

 	def get_average_rating(self):
 		# django create a review_set if you have a Review class
 			average = self.review_set.all().aggregate(Avg('rating'))['rating__avg']
 			if average == None:
 				return average
			else:
				return int(average)

	def get_reviews(self):
		return self.review_set.all()
		# this will return a list of reviews


class Review(models.Model):
	location = models.ForeignKey(Location)
	user = models.ForeignKey(User)
 	description = models.TextField(null=True, blank=True)
 	rating = models.IntegerField(choices=RATING_CHOICES, null=True, blank=True)
 	created_at = models.DateTimeField(auto_now_add=True)
 
  	def __unicode__(self):
 		return str(self.user) + ' / ' + self.created_at.strftime("%B %d, %Y") + ' / ' + str(self.rating)

templates/location/detail.html
{% extends "base/theme.html" %}
<!-- {% load staticfiles %}
<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet"> 
Now we the extend these 2 lines are already included
-->
    {% block gmaps %}
    <script src="{% static "js/maps.js" %}"></script>
    {% endblock %}


{% block main_content %}

<!-- Layer date for the location -->
<div class="data-layer">
    <ul>
        <li class="location-data" data-latitude="{{ location.position.latitude }}" data-longitude="{{ location.position.longitude }}">{{ location.title }}</li>
    </ul>
</div>
<!-- End of Layer date for the location -->


<div class="row main-content">
	<div class="col-md-2"></div>
	<div class="col-md-8">

		<div class="row">
			<div class="col-md-8">
			<h3><a href="{{ location.get_absolute_url }}">{{ location.title }}</a></h3>
			</div>
			<div class="col-md-4 text-right">
			<h3>{% include 'base/rating.html' with rating=location.get_average_rating %}</h3>
			</div>

<div class="col-md-4 panel">
 <div class="wide-map short-map" id="map"></div>
 <div class="col-md-3"></div>
 <div class="col-md-6 text-center">
 <br>
 {% if location.address %}<p>{{ location.address }}</p>{% endif %}
 {% if location.phone %}<p>{{ location.phone }}</p>{% endif %}
 {% if location.website %}<p><a href="{{ location.website }}">{{ location.website }}</a></p>{% endif %}
 </div>
 <div class="col-md-3"></div>
 </div>

			<div class="col-md-12">
				{% if location.address %}<p><b>Location: </b>{{ location.address }}</p>{% endif %}
				{% if location.hours %}<p>{{ location.hours }}</p>{% endif %}

				{% include 'location/specifics.html' with location=location %}


				<p>{{ location.description }}</p>
				{% if location.image_file %}
				<img class="img-responsive" src="{{ location.image_file.url }}"></img>
				{% endif %}
			</div>
			<div class="col-md-12">
				{% if user.is_authenticated and user.is_staff %}
				<br><a type="button" href="{% url 'location_update' pk=location.id %}" class="btn btn-default pull-left">Edit</a>
				{% endif %}
				{% if user.is_authenticated %}
					{% if user_review %}
					<a type="button" href="{% url 'review_update' pk=location.id %}" class="btn btn-default pull-left">Update Review</a>
					{% else %}
					<a type="button" href="{% url 'review_create' pk=location.id %}" class="btn btn-default pull-left">Create Review</a>
					{% endif %}
				{% endif %}
			</div>
			<div class="col-md-12">
				{% for review in location.get_reviews %}
					{% include 'base/review.html' with location=location %}
<!-- 				The first location is the variable in review.html page. The second location is the value from this page
 -->				{% endfor %}
			</div>
		</div> 
	</div>
	<div class="col-md-2"></div>
</div>
{% endblock %}

templates/location/list.html
{% extends "base/theme.html" %}
{% load bootstrap_pagination %}
<!-- {% load staticfiles %}
<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet"> 
Now we the extend these 2 lines are already included
-->
    {% block gmaps %}
    <script src="{% static "js/maps.js" %}"></script>
    {% endblock %}

{% block main_content %}

<!-- Now we will list all location geposition as a list so we can put them into a global map 
data-layer class is to prevent the data to be shown, but data are still there -->

<div class="data-layer">
	<ul>
		{% for location in object_list %}
			<li class="location-data" data-latitude="{{ location.position.latitude }}" data-longitude="{{ location.position.longitude }}" data-id="{{ location.id }}">
				{{ location.title }} </li>
		{% endfor %}
	</ul>
</div>

<div id="map" class="wide-map"></div>

<!-- end of the loop --> 

<div class="row main-content">
	<div class="col-md-2"></div>
	<div class="col-md-8">
		{% for location in object_list %}
		<!-- 		<div class='panel'> 
		commented to remove the box around this zone
		-->
		<div class="row">
	 		<div class="col-md-8">
			<h3><a href="{{ location.get_absolute_url }}">{{ location.title }}</a></h3>
			</div>
			<div class="col-md-4 text-right">
				<h3>{% include 'base/rating.html' with rating=location.get_average_rating %}</h3>
			</div>
			<div class="col-md-12">

			{% if location.address %}<p><b>Location:</b>{{ location.address }}</p>{% endif %}
			{% if location.address %}<p>{{ location.hours }}</p>{% endif %}

			{% include 'location/specifics.html' with location=location %}

			<p>{{ location.description }}</p>
			{% if location.image_file %}<img class="img-responsive" src="{{ location.image_file.url }}"></img>{% endif %}
			</div>
		</div>
		{% endfor %}
	</div>
	<div class="col-md-2"></div>
</div>
{% endblock %}

{% block pagination %}
{% bootstrap_paginate page_obj range=10 show_prev_next="false" show_first_last="true" %}
{% endblock %}

templates/location/specifics.html
<div class="row">
<div class="col-md-4">
 
<p><b>WIFI: </b>{% if location.wifi %}{{ location.get_wifi_display }}{% else %}----{% endif %}</p>
<p><b>Seating: </b>{% if location.seating %}{{ location.get_seating_display }}{% else %}----{% endif %}</p>
<p><b>Outlets: </b>{% if location.outlets %}{{ location.get_outlets_display }}{% else %}----{% endif %}</p>
<p><b>Bathrooms: </b>{% if location.bathrooms %}{{ location.get_bathrooms_display }}{% else %}----{% endif %}</p>
</div>
<div class="col-md-4">
<p><b>Coffee: </b>{% if location.coffee %}{{ location.get_coffee_display }}{% else %}----{% endif %}</p>
<p><b>Alcohol: </b>{% if location.alcohol %}{{ location.get_alcohol_display }}{% else %}----{% endif %}</p>
<p><b>Outdoor Seating: </b>{% if location.outdoor %}{{ location.get_outdoor_display }}{% else %}----{% endif %}</p>
<p><b>Food: </b>{% if location.food %}{{ location.get_food_display }}{% else %}----{% endif %}</p>
</div>
</div>